version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: go.dockerfile
    image: golang:1.10.3
    command: go run ginserver/main.go
    ports:
      - "8000:8000"
    links:
      - neo4j
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:3.4.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/admin
